### ISSUE TITLE
nativescript-nativechat not found in JS projects

### ISSUE THREAD

**Issue by tjvantoll** [darvinai/nativescript-plugin#4]
### If the demo apps cannot help and there is no issue for your problem, tell us about it
Please, ensure your title is less than 63 characters long and starts with a capital
letter.

### Which platform(s) does your issue occur on?
I’m testing on an iOS simulator.

### Please, provide the following version numbers that your issue occurs with:

- CLI: 4.1.0
- Cross-platform modules: 4.1.0
- Runtime(s): 4.1.0
- Plugin(s): Only this plugin

### Please, tell us how to recreate the issue in as much detail as possible. 
Describe the steps to reproduce it.

```
tns create ChatTest
cd ChatTest
```

Replace the `main-page.xml` and `main-page.js` files with the two code snippets from https://github.com/darvinai/nativescript-plugin#javascript.

```
tns run ios
```

Expected: I see the NativeChat widget.

Actual: I get this error:

```
JavaScript error:
file:///app/tns_modules/tns-core-modules/ui/builder/builder.js:244:56: JS ERROR Error: Building UI from XML. @file:///app/app-root.xml:1:1
> Building UI from XML. @file:///app/main-page.xml:2:5
> Module '/Users/tj/Library/Developer/CoreSimulator/Devices/2A39C5B1-A057-42F5-B53E-2638A4DDAE22/data/Containers/Bundle/Application/ED1F9F38-9A74-4D68-81C3-B93084F8F175/ChatTest.app/app/@progress-nativechat/nativescript-nativechat' not found for element '@progress-nativechat/nativescript-nativechat:NativeChat'.
> Could not find module '/Users/tj/Library/Developer/CoreSimulator/Devices/2A39C5B1-A057-42F5-B53E-2638A4DDAE22/data/Containers/Bundle/Application/ED1F9F38-9A74-4D68-81C3-B93084F8F175/ChatTest.app/app/@progress-nativechat/nativescript-nativechat'. Computed path '/Users/tj/Library/Developer/CoreSimulator/Devices/2A39C5B1-A057-42F5-B53E-2638A4DDAE22/data/Containers/Bundle/Application/ED1F9F38-9A74-4D68-81C3-B93084F8F175/ChatTest.app/app/@progress-nativechat/nativescript-nativechat'
```

**Comment by tjvantoll** [comment]
Actually this might not be specific to JS as I’m getting a similar error in a new Angular project.

```
file:///app/app.module.js:7:24: JS ERROR Error: Could not find module '@progress-nativechat/nativescript-nativechat/angular'. Computed path '/Users/tj/Library/Developer/CoreSimulator/Devices/2A39C5B1-A057-42F5-B53E-2638A4DDAE22/data/Containers/Bundle/Application/59D24CEC-41CC-4175-B56F-BA58EE7D179F/ChatTestNg.app/app/tns_modules/@progress-nativechat/nativescript-nativechat/angular'.
```

**Comment by gugulete** [comment]
I have updated the plugin npm packages to use the latest NativeScript and Angular versions.
